language: java

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

jdk:
  - oraclejdk8

env:
  global:

before_install:

script:
  # disable integration and performance tests, since we don't have a MarkLogic instance to use
  - ./gradlew check -PskipIntegrationTest -PskipPerformanceTest

after_success:
  # codecov.io integration https://codecov.io/gh/marklogic-community/xqsync/branch/development
  - bash <(curl -s https://codecov.io/bash)
  # sonarqube.com https://sonarqube.com/dashboard?id=com.marklogic%3Amarklogic-corb%3Adevelopment
  - ./gradlew sonarqube -Dsonar.login=$SONAR_TOKEN -Dsonar.host.url=https://sonarqube.com
  # codacy https://www.codacy.com/app/mads-hansen/corb2/dashboard
  - ./gradlew codacyUpload
  # coveralls.io
  - ./gradlew jacocoTestReport coveralls -PskipIntegrationTest -PskipPerformanceTest

addons:
  sonarqube:
      branches:
        - master
        - develop