version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

  working_directory: ~/code

  environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    
  steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
        name: Download Dependencies
        command: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "build.gradle" }}
        
      # run tests!
      - run:
          name: Run Tests
          command: ./gradlew test

      # collect test results
      #- run: |
      #    mkdir -p /junit/
      #    find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} /junit/ \;
      #- store_test_results:
      #    path: /junit
      #- store_artifacts:
      #    path: /junit